In [33]:
from mecon.etl.dataset import DatasetDir
from mecon.app.current_data import WorkingDatasetDir
from mecon.tags.process import RuleExecutionPlanMonitor
from mecon.data.data_management import CachedFileDataManager
from mecon.tags import process

# datasets = WorkingDatasetDir()
datasets = DatasetDir(path=r"/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets")
datasets.dataset_names()

INFO:root:Adding 12 datasets from /Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/shared_backup'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/test'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/mydata'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/shared_monzoapi'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/shared'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/mydata_backup'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/v2'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/v2_dataset_test'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/v3'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/v2_backup'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/v2_dataset_test_monzo_api'. #info#filesystem
INFO:root:New dataset in path '/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/.idea'. #info#filesystem

['shared_backup',
 'test',
 'mydata',
 'shared_monzoapi',
 'shared',
 'mydata_backup',
 'v2',
 'v2_dataset_test',
 'v3',
 'v2_backup',
 'v2_dataset_test_monzo_api',
 '.idea']

## Calculating stats for dataset containing Monzo data

In [34]:
monzo_dataset = datasets.get_dataset('v2_dataset_test')
dm = CachedFileDataManager(monzo_dataset)
monzo_transactions, monzo_tags = dm.get_transactions(), dm.all_tags()

monitor = RuleExecutionPlanMonitor(dest_path_or_dataset='./monzo')
orep = process.OptimisedRuleExecutionPlanTagging(monzo_tags)
orep.create_rule_execution_plan()
orep.create_optimised_rule_execution_plan()
new_monzo_trans = orep.tag(monzo_transactions, monitor=monitor)

WARNING:root:spotify not in dependency mapping while calculating hierarchy. Will be replaced with 0
WARNING:root:giffgaff not in dependency mapping while calculating hierarchy. Will be replaced with 0
WARNING:root:Transfer not in dependency mapping while calculating hierarchy. Will be replaced with 0
INFO:root:Removed cycles from the graph. cycles=[], edges_to_remove=[], len(edges)=90, len(cleaned_edges)=90, len(new_tg.find_all_cycles())=0
INFO:root:[edge in cleaned_edges for edge in edges_to_remove]=[]
WARNING:root:spotify not in dependency mapping while calculating hierarchy. Will be replaced with 0
WARNING:root:giffgaff not in dependency mapping while calculating hierarchy. Will be replaced with 0
WARNING:root:Transfer not in dependency mapping while calculating hierarchy. Will be replaced with 0
INFO:root:Created 558 rules using 558 aliases.
INFO:root:create_rule_execution_plan took 0.003857135772705078 seconds to execute.
INFO:root:Reduce 211 conditions to 9 unique transformation operations
INFO:root:Expanded the plan with 9 transformations
INFO:root:Removed 154 redundant Conjunctions and 26 Disjunctions, going from 567 to 387 rules (reduced to 68% of the original size).
INFO:root:Deduplicated 387 rules down to 358 rules
INFO:root:Reduce 558 rules to 358 unique rules and 558 aliases.
INFO:root:create_optimised_rule_execution_plan took 0.010496854782104492 seconds to execute.
INFO:root:Applying 9 rules, with priority -1
Priority -1: 100%|██████████| 9/9 [00:00<00:00, 387.93it/s]
INFO:root:Applying 191 rules, with priority 0.0
Priority 0.0: 100%|██████████| 191/191 [00:00<00:00, 409.48it/s]
INFO:root:Applying 25 rules, with priority 0.2
Priority 0.2: 100%|██████████| 25/25 [00:00<00:00, 3827.48it/s]
INFO:root:Applying 18 rules, with priority 0.4
Priority 0.4: 100%|██████████| 18/18 [00:00<00:00, 4380.47it/s]
INFO:root:Applying 39 rules, with priority 0.8
Priority 0.8: 100%|██████████| 39/39 [00:00<00:00, 223.01it/s]
INFO:root:Applying 20 rules, with priority 1.1
Priority 1.1: 100%|██████████| 20/20 [00:00<00:00, 298.67it/s]
INFO:root:Applying 17 rules, with priority 1.2
Priority 1.2: 100%|██████████| 17/17 [00:00<00:00, 5044.44it/s]
INFO:root:Applying 7 rules, with priority 1.4
Priority 1.4: 100%|██████████| 7/7 [00:00<00:00, 2745.99it/s]
INFO:root:Applying 9 rules, with priority 1.8
Priority 1.8: 100%|██████████| 9/9 [00:00<00:00, 157.54it/s]
INFO:root:Applying 7 rules, with priority 2.1
Priority 2.1: 100%|██████████| 7/7 [00:00<00:00, 299.07it/s]
INFO:root:Applying 1 rules, with priority 2.2
Priority 2.2: 100%|██████████| 1/1 [00:00<00:00, 1886.78it/s]
INFO:root:Applying 2 rules, with priority 2.4
Priority 2.4: 100%|██████████| 2/2 [00:00<00:00, 2366.99it/s]
INFO:root:Applying 4 rules, with priority 2.8
Priority 2.8: 100%|██████████| 4/4 [00:00<00:00, 1371.70it/s]
INFO:root:Applying 5 rules, with priority 3.1
Priority 3.1: 100%|██████████| 5/5 [00:00<00:00, 366.40it/s]
INFO:root:Applying 1 rules, with priority 3.2
Priority 3.2: 100%|██████████| 1/1 [00:00<00:00, 1170.94it/s]
INFO:root:Applying 1 rules, with priority 3.4
Priority 3.4: 100%|██████████| 1/1 [00:00<00:00, 2104.52it/s]
INFO:root:Applying 2 rules, with priority 3.8
Priority 3.8: 100%|██████████| 2/2 [00:00<00:00, 1235.44it/s]
INFO:root:Saving calculation stats at monzo/calc_monitoring.csv
INFO:root:Saving operation stats at monzo/op_monitoring.csv
INFO:root:tag took 1.907240867614746 seconds to execute.

## Calculating stats for dataset containing Monzo API data

In [35]:
monzo_api_dataset = datasets.get_dataset('v2_dataset_test_monzo_api')
dm = CachedFileDataManager(monzo_api_dataset)
monzoapi_transactions, monzoapi_tags = dm.get_transactions(), dm.all_tags()

monitor = RuleExecutionPlanMonitor(dest_path_or_dataset='./monzo_api')
orep = process.OptimisedRuleExecutionPlanTagging(monzoapi_tags)
orep.create_rule_execution_plan()
orep.create_optimised_rule_execution_plan()
new_monzoapi_trans = orep.tag(monzoapi_transactions, monitor=monitor)

WARNING:root:spotify not in dependency mapping while calculating hierarchy. Will be replaced with 0
WARNING:root:giffgaff not in dependency mapping while calculating hierarchy. Will be replaced with 0
WARNING:root:Transfer not in dependency mapping while calculating hierarchy. Will be replaced with 0
INFO:root:Removed cycles from the graph. cycles=[], edges_to_remove=[], len(edges)=90, len(cleaned_edges)=90, len(new_tg.find_all_cycles())=0
INFO:root:[edge in cleaned_edges for edge in edges_to_remove]=[]
WARNING:root:spotify not in dependency mapping while calculating hierarchy. Will be replaced with 0
WARNING:root:giffgaff not in dependency mapping while calculating hierarchy. Will be replaced with 0
WARNING:root:Transfer not in dependency mapping while calculating hierarchy. Will be replaced with 0
INFO:root:Created 558 rules using 558 aliases.
INFO:root:create_rule_execution_plan took 0.0033309459686279297 seconds to execute.
INFO:root:Reduce 211 conditions to 9 unique transformation operations
INFO:root:Expanded the plan with 9 transformations
INFO:root:Removed 154 redundant Conjunctions and 26 Disjunctions, going from 567 to 387 rules (reduced to 68% of the original size).
INFO:root:Deduplicated 387 rules down to 359 rules
INFO:root:Reduce 558 rules to 359 unique rules and 558 aliases.
INFO:root:create_optimised_rule_execution_plan took 0.009824037551879883 seconds to execute.
INFO:root:Applying 9 rules, with priority -1
Priority -1: 100%|██████████| 9/9 [00:00<00:00, 208.84it/s]
INFO:root:Applying 192 rules, with priority 0.0
Priority 0.0: 100%|██████████| 192/192 [00:00<00:00, 233.96it/s]
INFO:root:Applying 25 rules, with priority 0.2
Priority 0.2: 100%|██████████| 25/25 [00:00<00:00, 3200.59it/s]
INFO:root:Applying 18 rules, with priority 0.4
Priority 0.4: 100%|██████████| 18/18 [00:00<00:00, 4473.13it/s]
INFO:root:Applying 39 rules, with priority 0.8
Priority 0.8: 100%|██████████| 39/39 [00:00<00:00, 257.89it/s]
INFO:root:Applying 20 rules, with priority 1.1
Priority 1.1: 100%|██████████| 20/20 [00:00<00:00, 282.75it/s]
INFO:root:Applying 17 rules, with priority 1.2
Priority 1.2: 100%|██████████| 17/17 [00:00<00:00, 4684.53it/s]
INFO:root:Applying 7 rules, with priority 1.4
Priority 1.4: 100%|██████████| 7/7 [00:00<00:00, 2946.03it/s]
INFO:root:Applying 9 rules, with priority 1.8
Priority 1.8: 100%|██████████| 9/9 [00:00<00:00, 172.84it/s]
INFO:root:Applying 7 rules, with priority 2.1
Priority 2.1: 100%|██████████| 7/7 [00:00<00:00, 82.83it/s]
INFO:root:Applying 1 rules, with priority 2.2
Priority 2.2: 100%|██████████| 1/1 [00:00<00:00, 1660.45it/s]
INFO:root:Applying 2 rules, with priority 2.4
Priority 2.4: 100%|██████████| 2/2 [00:00<00:00, 1271.19it/s]
INFO:root:Applying 4 rules, with priority 2.8
Priority 2.8: 100%|██████████| 4/4 [00:00<00:00, 930.62it/s]
INFO:root:Applying 5 rules, with priority 3.1
Priority 3.1: 100%|██████████| 5/5 [00:00<00:00, 343.00it/s]
INFO:root:Applying 1 rules, with priority 3.2
Priority 3.2: 100%|██████████| 1/1 [00:00<00:00, 1264.11it/s]
INFO:root:Applying 1 rules, with priority 3.4
Priority 3.4: 100%|██████████| 1/1 [00:00<00:00, 2020.38it/s]
INFO:root:Applying 2 rules, with priority 3.8
Priority 3.8: 100%|██████████| 2/2 [00:00<00:00, 49.62it/s]
INFO:root:Saving calculation stats at monzo_api/calc_monitoring.csv
INFO:root:Saving operation stats at monzo_api/op_monitoring.csv
INFO:root:tag took 2.694601058959961 seconds to execute.

In [36]:
import pandas as pd
monzo_calcs = pd.read_csv("/Users/wimpole/PycharmProjects/mecon/docs/scripts/monzo_to_monzo_api_migrations/monzo/calc_monitoring.csv", index_col=None)
monzoapi_calcs = pd.read_csv("/Users/wimpole/PycharmProjects/mecon/docs/scripts/monzo_to_monzo_api_migrations/monzo_api/calc_monitoring.csv", index_col=None)
monzo_calcs.shape, monzoapi_calcs.shape

((7643, 321), (7949, 322))

## Finding common IDs between the two datasets

In [37]:
common_ids = set(monzo_calcs['id']).intersection(monzoapi_calcs['id'])
len(common_ids)

6315

## Finding common columns between the two datasets

In [49]:
common_cols = list(set(monzo_calcs.columns).intersection(set(monzoapi_calcs.columns)))
common_cols

['description.none',
 'lower(description) contains eleni exarchou',
 'lower(description) contains category: entertainment',
 'tags contains Income',
 'lower(description) contains michail',
 'tags_list_1.8',
 'lower(tags) contains giffgaff',
 'lower(description) contains transfer',
 'lower(description) contains budgetair',
 'upper(description) contains ELECTRIC BRIXTON',
 'lower(description) contains syn ka',
 'lower(description) contains aldi',
 'lower(description) contains ryanair',
 'new_tags_list',
 'lower(description) contains tfl',
 'lower(description) contains urban outfitters',
 'lower(description) contains exchange',
 'lower(description) contains galaxias',
 'tags contains Food delivery',
 'lower(description) contains stansted express',
 'split_comma(tags) in_csv Monzo',
 'split_comma(tags) in_csv My transfers,Alpha Bank,Friends transfers,Currency exchange,Home Bills,Rent',
 'tags_added_3.8',
 'amount.none',
 'lower(description) contains syn.ka',
 'lower(description) contains sainsbury',
 'description contains Kontzedakis',
 'upper(description) contains GRADY ALWYNE',
 'split_comma(tags) in_csv Finallot Income',
 'description contains Top-Up by *0852',
 'id in RVLTd20200821t110751an22000i3306',
 'description contains ITV',
 'amount equal 450',
 'lower(description) contains kontzedaki d',
 'lower(description) contains lidl',
 'upper(description) contains DELOITTE LLP CR',
 'lower(description) contains bank:revolut',
 'description contains bank:HSBC,',
 'lower(description) contains uber',
 'lower(description) contains sakkadakis',
 'lower(description) contains thames water',
 'tags_added_1.8',
 'lower(description) contains wizz air',
 'hour(datetime) greater_equal 12',
 'hour(datetime) greater_equal 8',
 'lower(description) contains kontzeda',
 'lower(description) contains restaurant',
 'description contains Revolut**4562*',
 'description contains ANALITIKA ONE',
 'lower(description) contains virgin media',
 'tags contains Online orders',
 'lower(description) contains fabric',
 'split_comma(tags) in_csv Super Market',
 'str(datetime) greater 2023-04-06',
 'description contains DIMITRIOS KONTZEDA TO REVOLUT SO',
 'lower(description) contains bulb energy',
 'lower(description) contains drumshed',
 'lower(description) contains merieme katsani',
 'lower(description) contains mcdonald',
 'amount greater 80',
 'description contains 🍸',
 'amount equal 550',
 'id.none',
 'id not_contains TRD212d20250211t163510ap364274i7',
 'str(datetime) greater 2021-01-01',
 'str(datetime) less 2023-04-07',
 'tags contains Flight tickets',
 'lower(description) contains santander cycles',
 'tags_list_3.8',
 'upper(description) contains WWW.HP.COM',
 'hour(datetime) less 12',
 'lower(description) contains cosmote',
 'lower(description) contains tavern',
 'lower(description) contains blue star ferries',
 'lower(description) contains ferry',
 'lower(description) contains koinopraxia anek',
 'upper(description) contains VILLAGE UNDERGROUND',
 'lower(description) contains waitrose',
 'lower(description) contains dimitri',
 'lower(description) contains cash',
 'lower(description) contains airbnb',
 'lower(description) contains advanced optical',
 'lower(description) not_contains cash at tesco',
 'lower(description) contains bank:monzo',
 'tags contains Therapy',
 'lower(description) contains ally',
 'lower(description) contains arms',
 'split_comma(tags) in_csv Eating out',
 'lower(description) contains olympic',
 'abs(amount) greater 34',
 'description contains INSTABOOK LTD',
 'amount',
 'tags contains Too good to go',
 'amount equal 600',
 'lower(description) contains deli ',
 'lower(description) contains lime',
 'lower(description) contains fragkiadakis',
 'lower(description) contains from georgios',
 'lower(description) contains nando',
 'tags_added_0.8',
 'lower(description) contains just',
 'lower(description) contains marks',
 'lower(description) contains lexington',
 'lower(description) contains vision express',
 'description contains To Dimitrios Kontzedakis',
 'lower(description) contains easyjet',
 'lower(description) contains elif food',
 'upper(description) contains TYPE: TRANSFER',
 'datetime.str',
 'lower(description) contains ebay',
 'lower(description) contains duke',
 'description contains Dimitrios Kontzeda Sent from Revolut CR',
 'lower(description) contains amznmktplace',
 'description contains bank:TRD212, action: Deposit',
 'lower(description) contains egg london',
 'currency',
 'lower(description) contains printworks',
 'lower(description) contains toogoodtog',
 'tags contains Rent',
 'tags contains Spending',
 'lower(description) contains jago',
 'description.lower',
 'lower(description) contains hostel',
 'lower(description) contains samsung',
 'lower(description) contains co-op',
 'amount.abs',
 'lower(description) contains tfl cycle hire',
 'lower(description) contains rose pub',
 'lower(description) contains anek lines',
 'description contains 🍺',
 'lower(description) contains jazz',
 'tags',
 'abs(amount) less 38',
 'lower(description) contains eat',
 'currency equal EUR',
 'tags_list_0.8',
 'lower(description) contains from eleni exarchou',
 'datetime.hour',
 'lower(description) contains h&m',
 'hour(datetime) greater_equal 20',
 'lower(description) contains hotel',
 'upper(description) contains RESIDENT ADVISOR',
 'lower(description) not_contains cash sainsby',
 'split_comma(tags) in_csv Revolut',
 'amount greater 0',
 'lower(description) contains 110 pennington street',
 'lower(description) contains joseph',
 'lower(description) contains tesco',
 'lower(description) contains nisa',
 'tags not_contains BorisBike',
 'description contains bank:HSBC, Amanmeet Singh Bha rent BP',
 'str(datetime) greater 2023-01-10',
 'lower(description) contains giffgaff',
 'lower(description) contains supermercats',
 'lower(description) contains dream bags',
 'lower(description) contains kfc',
 'upper(description) contains THE CURRENCY CLOUD LTD',
 'description contains Dimitrios Kontzeda Sent from Monzo CR',
 'lower(description) contains masoutis',
 'lower(description) contains spotify',
 'lower(description) contains vasilopoulos',
 'split_comma(tags) in_csv Home Bills',
 'lower(description) contains british airways',
 'lower(description) contains sklavenitis',
 'lower(description) contains efood',
 'lower(description) contains asda',
 'currency.none',
 'tags contains Accomodation',
 'split_comma(tags) in_csv HSBC',
 'amount greater_equal 400',
 'lower(description) contains eating out',
 'id in RVLTd20220810t190439an57500i32748,RVLTd20220810t211424an57500i32752,RVLTd20220810t190500an75000i32749,RVLTd20230421t094803an40000i33395,RVLTd20230301t141958an38000i33320,RVLTd20220810t190439an57500i32747, RVLTd20200106t181345an50000i36, MZNd20200203t133216an40000itx_00009rf6iRCr2zJCr2zTEH, RVLTd20200203t132435an25349i354, RVLTd20200203t140951an10349i355, MZNd20200301t011821an40000itx_00009sY15bSTBTrWFgzFIH, MZNd20200302t200328an20000itx_00009sbi0yOVMNPxgVKsFt, MZNd20200302t200239an10000itx_00009sbhwQv1sYDESh6CFl, RVLTd20200327t194415an7000i374',
 'description contains DIMITRIS MONZO WEEKLY SO',
 'split_comma(tags) in_csv Rent',
 'hour(datetime) less 20',
 'lower(description) contains shacklewell',
 'lower(description) contains karimpidis',
 'datetime',
 'lower(description) contains spencer',
 'lower(description) contains amazon',
 'amount less -40',
 'description contains EDF ENERGY-ECOM PLYMOUTH VIS',
 'lower(description) contains morrisons',
 'lower(description) not_contains netflix',
 'lower(description) contains karamanos',
 'lower(description) contains zara',
 'abs(amount) greater 30',
 'description.upper',
 'lower(description) contains supersave',
 'lower(description) contains trainline',
 'description contains bank:TRD212',
 'split_comma(tags) in_csv Revolut,Monzo,HSBC',
 'tags contains Airbnb',
 'upper(description) contains IGBONS',
 'split_comma(tags) in_csv ITV income',
 'id in RVLTd20230523t140232an4550i33445,RVLTd20230617t141643ap18794i33942',
 'lower(description) contains polu poke',
 'tags not_contains Transfer',
 'lower(description) contains sky express',
 'description contains bank:INVENG',
 'description contains Payment from Kontzedaki',
 'upper(description) contains PEACHEY',
 'lower(description) contains category: eating out',
 'lower(description) contains fold',
 'description contains Dr Sina Motesharei rent BP',
 'lower(description) contains brewpub',
 'lower(description) contains asos',
 'tags_list_2.8',
 'split_comma(tags) in_csv Deloitte income',
 'abs(amount) greater 25',
 'id in RVLTd20200824t164853an3051i3307,RVLTd20200824t110611an2391i3309',
 'amount less 0.0',
 'upper(description) contains MY REVO',
 'split_comma(tags) in_csv TFL,BorisBike,LimeBike,Uber Taxi',
 'description',
 'amount less 0',
 'lower(description) contains theodorouleas',
 'upper(description) contains VILLAGE 512',
 'tags not_contains Therapy',
 'lower(description) contains sideris',
 'id',
 'tags_added_2.8',
 'lower(description) contains marsel katsani',
 'tags not_contains Online payments',
 'amount_cur',
 'lower(description) contains poundland',
 'amount equal 575',
 'lower(description) contains e food',
 'tags not_contains Income',
 'amount greater_equal 600',
 'lower(description) contains kiwi.com',
 'description contains bank:HSBCSVR',
 'lower(description) contains jetbrains',
 'lower(description) contains supermarket',
 'lower(description) contains stefano di tommaso',
 'hour(datetime) less 8',
 'lower(description) contains paypal',
 'tags contains Revolut',
 'lower(description) contains exarchou',
 'tags contains Monzo',
 'lower(tags) contains spotify',
 'lower(description) contains pophams',
 'old_tags',
 'lower(description) contains booking',
 'description contains To Dimitrios (Alpha) Kontzedakis',
 'description contains EDF',
 'abs(amount) less 28',
 'amount greater 2000']

## Filtering out column with no interest for this task

Ideally we want to keep only leaf rules, that act upon the basic transaction fields

In [51]:
fields = ['amount', 'datetime', 'description', 'amount_cur', 'currency', 'tags']

cols_of_interest = common_cols.copy()

for col in common_cols:
    for field in fields:
        if col == field:
            print(f"REMOVED: column '{col}' is field")
            cols_of_interest.remove(col)
            break
        elif col.startswith(field+'.'):
            print(f"REMOVED: column '{col}' is transformation")
            cols_of_interest.remove(col)
            break
        elif col.startswith('tags_list') or col.startswith('tags_added') or col.startswith('new_tags_list'):
            print(f"REMOVED: column '{col}' is tags column")
            cols_of_interest.remove(col)
            break
        elif '_tags' in col:
            print(f"REMOVED: column '{col}' is _tags column")
            cols_of_interest.remove(col)
            break
        # else:
        #    print(f"ADDED: column {col} is VALID")
cols_of_interest

REMOVED: column 'description.none' is transformation
REMOVED: column 'tags_list_1.8' is tags column
REMOVED: column 'new_tags_list' is tags column
REMOVED: column 'tags_added_3.8' is tags column
REMOVED: column 'amount.none' is transformation
REMOVED: column 'tags_added_1.8' is tags column
REMOVED: column 'tags_list_3.8' is tags column
REMOVED: column 'amount' is field
REMOVED: column 'tags_added_0.8' is tags column
REMOVED: column 'datetime.str' is transformation
REMOVED: column 'currency' is field
REMOVED: column 'description.lower' is transformation
REMOVED: column 'amount.abs' is transformation
REMOVED: column 'tags' is field
REMOVED: column 'tags_list_0.8' is tags column
REMOVED: column 'datetime.hour' is transformation
REMOVED: column 'currency.none' is transformation
REMOVED: column 'datetime' is field
REMOVED: column 'description.upper' is transformation
REMOVED: column 'tags_list_2.8' is tags column
REMOVED: column 'description' is field
REMOVED: column 'tags_added_2.8' is tags column
REMOVED: column 'amount_cur' is field
REMOVED: column 'old_tags' is _tags column

['lower(description) contains eleni exarchou',
 'lower(description) contains category: entertainment',
 'tags contains Income',
 'lower(description) contains michail',
 'lower(tags) contains giffgaff',
 'lower(description) contains transfer',
 'lower(description) contains budgetair',
 'upper(description) contains ELECTRIC BRIXTON',
 'lower(description) contains syn ka',
 'lower(description) contains aldi',
 'lower(description) contains ryanair',
 'lower(description) contains tfl',
 'lower(description) contains urban outfitters',
 'lower(description) contains exchange',
 'lower(description) contains galaxias',
 'tags contains Food delivery',
 'lower(description) contains stansted express',
 'split_comma(tags) in_csv Monzo',
 'split_comma(tags) in_csv My transfers,Alpha Bank,Friends transfers,Currency exchange,Home Bills,Rent',
 'lower(description) contains syn.ka',
 'lower(description) contains sainsbury',
 'description contains Kontzedakis',
 'upper(description) contains GRADY ALWYNE',
 'split_comma(tags) in_csv Finallot Income',
 'description contains Top-Up by *0852',
 'id in RVLTd20200821t110751an22000i3306',
 'description contains ITV',
 'amount equal 450',
 'lower(description) contains kontzedaki d',
 'lower(description) contains lidl',
 'upper(description) contains DELOITTE LLP CR',
 'lower(description) contains bank:revolut',
 'description contains bank:HSBC,',
 'lower(description) contains uber',
 'lower(description) contains sakkadakis',
 'lower(description) contains thames water',
 'lower(description) contains wizz air',
 'hour(datetime) greater_equal 12',
 'hour(datetime) greater_equal 8',
 'lower(description) contains kontzeda',
 'lower(description) contains restaurant',
 'description contains Revolut**4562*',
 'description contains ANALITIKA ONE',
 'lower(description) contains virgin media',
 'tags contains Online orders',
 'lower(description) contains fabric',
 'split_comma(tags) in_csv Super Market',
 'str(datetime) greater 2023-04-06',
 'description contains DIMITRIOS KONTZEDA TO REVOLUT SO',
 'lower(description) contains bulb energy',
 'lower(description) contains drumshed',
 'lower(description) contains merieme katsani',
 'lower(description) contains mcdonald',
 'amount greater 80',
 'description contains 🍸',
 'amount equal 550',
 'id.none',
 'id not_contains TRD212d20250211t163510ap364274i7',
 'str(datetime) greater 2021-01-01',
 'str(datetime) less 2023-04-07',
 'tags contains Flight tickets',
 'lower(description) contains santander cycles',
 'upper(description) contains WWW.HP.COM',
 'hour(datetime) less 12',
 'lower(description) contains cosmote',
 'lower(description) contains tavern',
 'lower(description) contains blue star ferries',
 'lower(description) contains ferry',
 'lower(description) contains koinopraxia anek',
 'upper(description) contains VILLAGE UNDERGROUND',
 'lower(description) contains waitrose',
 'lower(description) contains dimitri',
 'lower(description) contains cash',
 'lower(description) contains airbnb',
 'lower(description) contains advanced optical',
 'lower(description) not_contains cash at tesco',
 'lower(description) contains bank:monzo',
 'tags contains Therapy',
 'lower(description) contains ally',
 'lower(description) contains arms',
 'split_comma(tags) in_csv Eating out',
 'lower(description) contains olympic',
 'abs(amount) greater 34',
 'description contains INSTABOOK LTD',
 'tags contains Too good to go',
 'amount equal 600',
 'lower(description) contains deli ',
 'lower(description) contains lime',
 'lower(description) contains fragkiadakis',
 'lower(description) contains from georgios',
 'lower(description) contains nando',
 'lower(description) contains just',
 'lower(description) contains marks',
 'lower(description) contains lexington',
 'lower(description) contains vision express',
 'description contains To Dimitrios Kontzedakis',
 'lower(description) contains easyjet',
 'lower(description) contains elif food',
 'upper(description) contains TYPE: TRANSFER',
 'lower(description) contains ebay',
 'lower(description) contains duke',
 'description contains Dimitrios Kontzeda Sent from Revolut CR',
 'lower(description) contains amznmktplace',
 'description contains bank:TRD212, action: Deposit',
 'lower(description) contains egg london',
 'lower(description) contains printworks',
 'lower(description) contains toogoodtog',
 'tags contains Rent',
 'tags contains Spending',
 'lower(description) contains jago',
 'lower(description) contains hostel',
 'lower(description) contains samsung',
 'lower(description) contains co-op',
 'lower(description) contains tfl cycle hire',
 'lower(description) contains rose pub',
 'lower(description) contains anek lines',
 'description contains 🍺',
 'lower(description) contains jazz',
 'abs(amount) less 38',
 'lower(description) contains eat',
 'currency equal EUR',
 'lower(description) contains from eleni exarchou',
 'lower(description) contains h&m',
 'hour(datetime) greater_equal 20',
 'lower(description) contains hotel',
 'upper(description) contains RESIDENT ADVISOR',
 'lower(description) not_contains cash sainsby',
 'split_comma(tags) in_csv Revolut',
 'amount greater 0',
 'lower(description) contains 110 pennington street',
 'lower(description) contains joseph',
 'lower(description) contains tesco',
 'lower(description) contains nisa',
 'tags not_contains BorisBike',
 'description contains bank:HSBC, Amanmeet Singh Bha rent BP',
 'str(datetime) greater 2023-01-10',
 'lower(description) contains giffgaff',
 'lower(description) contains supermercats',
 'lower(description) contains dream bags',
 'lower(description) contains kfc',
 'upper(description) contains THE CURRENCY CLOUD LTD',
 'description contains Dimitrios Kontzeda Sent from Monzo CR',
 'lower(description) contains masoutis',
 'lower(description) contains spotify',
 'lower(description) contains vasilopoulos',
 'split_comma(tags) in_csv Home Bills',
 'lower(description) contains british airways',
 'lower(description) contains sklavenitis',
 'lower(description) contains efood',
 'lower(description) contains asda',
 'tags contains Accomodation',
 'split_comma(tags) in_csv HSBC',
 'amount greater_equal 400',
 'lower(description) contains eating out',
 'id in RVLTd20220810t190439an57500i32748,RVLTd20220810t211424an57500i32752,RVLTd20220810t190500an75000i32749,RVLTd20230421t094803an40000i33395,RVLTd20230301t141958an38000i33320,RVLTd20220810t190439an57500i32747, RVLTd20200106t181345an50000i36, MZNd20200203t133216an40000itx_00009rf6iRCr2zJCr2zTEH, RVLTd20200203t132435an25349i354, RVLTd20200203t140951an10349i355, MZNd20200301t011821an40000itx_00009sY15bSTBTrWFgzFIH, MZNd20200302t200328an20000itx_00009sbi0yOVMNPxgVKsFt, MZNd20200302t200239an10000itx_00009sbhwQv1sYDESh6CFl, RVLTd20200327t194415an7000i374',
 'description contains DIMITRIS MONZO WEEKLY SO',
 'split_comma(tags) in_csv Rent',
 'hour(datetime) less 20',
 'lower(description) contains shacklewell',
 'lower(description) contains karimpidis',
 'lower(description) contains spencer',
 'lower(description) contains amazon',
 'amount less -40',
 'description contains EDF ENERGY-ECOM PLYMOUTH VIS',
 'lower(description) contains morrisons',
 'lower(description) not_contains netflix',
 'lower(description) contains karamanos',
 'lower(description) contains zara',
 'abs(amount) greater 30',
 'lower(description) contains supersave',
 'lower(description) contains trainline',
 'description contains bank:TRD212',
 'split_comma(tags) in_csv Revolut,Monzo,HSBC',
 'tags contains Airbnb',
 'upper(description) contains IGBONS',
 'split_comma(tags) in_csv ITV income',
 'id in RVLTd20230523t140232an4550i33445,RVLTd20230617t141643ap18794i33942',
 'lower(description) contains polu poke',
 'tags not_contains Transfer',
 'lower(description) contains sky express',
 'description contains bank:INVENG',
 'description contains Payment from Kontzedaki',
 'upper(description) contains PEACHEY',
 'lower(description) contains category: eating out',
 'lower(description) contains fold',
 'description contains Dr Sina Motesharei rent BP',
 'lower(description) contains brewpub',
 'lower(description) contains asos',
 'split_comma(tags) in_csv Deloitte income',
 'abs(amount) greater 25',
 'id in RVLTd20200824t164853an3051i3307,RVLTd20200824t110611an2391i3309',
 'amount less 0.0',
 'upper(description) contains MY REVO',
 'split_comma(tags) in_csv TFL,BorisBike,LimeBike,Uber Taxi',
 'amount less 0',
 'lower(description) contains theodorouleas',
 'upper(description) contains VILLAGE 512',
 'tags not_contains Therapy',
 'lower(description) contains sideris',
 'id',
 'lower(description) contains marsel katsani',
 'tags not_contains Online payments',
 'lower(description) contains poundland',
 'amount equal 575',
 'lower(description) contains e food',
 'tags not_contains Income',
 'amount greater_equal 600',
 'lower(description) contains kiwi.com',
 'description contains bank:HSBCSVR',
 'lower(description) contains jetbrains',
 'lower(description) contains supermarket',
 'lower(description) contains stefano di tommaso',
 'hour(datetime) less 8',
 'lower(description) contains paypal',
 'tags contains Revolut',
 'lower(description) contains exarchou',
 'tags contains Monzo',
 'lower(tags) contains spotify',
 'lower(description) contains pophams',
 'lower(description) contains booking',
 'description contains To Dimitrios (Alpha) Kontzedakis',
 'description contains EDF',
 'abs(amount) less 28',
 'amount greater 2000']

## creating the filtered datasets

In [40]:
monzo = monzo_calcs[monzo_calcs['id'].isin(common_ids)].sort_values('id')[cols_of_interest].reset_index(drop=True)
monzoapi = monzoapi_calcs[monzoapi_calcs['id'].isin(common_ids)].sort_values('id')[cols_of_interest].reset_index(drop=True)
monzo.shape, monzoapi.shape

((6315, 225), (6315, 225))

In [41]:
# monzo['tags'] = monzo['tags'].apply(lambda s:set(s.split(',')))
# monzoapi['tags'] = monzoapi['tags'].apply(lambda s:set(s.split(',')))
# (monzo['tags'] == monzoapi['tags']).sum()

## Comparison dataframe

In [42]:
comps = monzo.compare(monzoapi)
# comps.columns = [c[0]+' ('+('monzo' if c[1]=='self' else 'monzoapi')+')' for c in comps.columns]
# cols = list({c for c in comps.columns})
cols = list({c[0] for c in comps.columns})

comps['id'] = monzo['id']
comps

     lower(description) contains category: entertainment        \
                                                    self other
974                                                 NaN    NaN
975                                                 NaN    NaN
976                                                 NaN    NaN
977                                                 NaN    NaN
978                                                 NaN    NaN
...                                                 ...    ...
5692                                                NaN    NaN
5693                                                NaN    NaN
5708                                                NaN    NaN
6040                                                NaN    NaN
6041                                                NaN    NaN

     lower(description) contains transfer        \
                                     self other
974                                 False  True
975                                   NaN   NaN
976                                 False  True
977                                   NaN   NaN
978                                   NaN   NaN
...                                   ...   ...
5692                                  NaN   NaN
5693                                  NaN   NaN
5708                                  NaN   NaN
6040                                  NaN   NaN
6041                                  NaN   NaN

     lower(description) contains tfl       tags contains Food delivery        \
                                self other                        self other
974                              NaN   NaN                         NaN   NaN
975                              NaN   NaN                         NaN   NaN
976                              NaN   NaN                         NaN   NaN
977                              NaN   NaN                         NaN   NaN
978                              NaN   NaN                         NaN   NaN
...                              ...   ...                         ...   ...
5692                             NaN   NaN                         NaN   NaN
5693                             NaN   NaN                         NaN   NaN
5708                             NaN   NaN                         NaN   NaN
6040                             NaN   NaN                         NaN   NaN
6041                             NaN   NaN                         NaN   NaN

     split_comma(tags) in_csv My transfers,Alpha Bank,Friends transfers,Currency exchange,Home Bills,Rent  \
                                                                                                     self
974                                                 NaN
975                                                 NaN
976                                                 NaN
977                                                 NaN
978                                                 NaN
...                                                 ...
5692                                                NaN
5693                                                NaN
5708                                                NaN
6040                                                NaN
6041                                                NaN

            ... tags not_contains Transfer  \
     other  ...                      other
974    NaN  ...                        NaN
975    NaN  ...                        NaN
976    NaN  ...                        NaN
977    NaN  ...                        NaN
978    NaN  ...                        NaN
...    ...  ...                        ...
5692   NaN  ...                        NaN
5693   NaN  ...                        NaN
5708   NaN  ...                        NaN
6040   NaN  ...                        NaN
6041   NaN  ...                        NaN

     lower(description) contains category: eating out        \
                                                 self other
974                                               NaN   NaN
975                                               NaN   NaN
976                                               NaN   NaN
977                                               NaN   NaN
978                                               NaN   NaN
...                                               ...   ...
5692                                              NaN   NaN
5693                                              NaN   NaN
5708                                              NaN   NaN
6040                                              NaN   NaN
6041                                              NaN   NaN

     split_comma(tags) in_csv TFL,BorisBike,LimeBike,Uber Taxi         \
                                                          self  other
974                                                 NaN           NaN
975                                                 NaN           NaN
976                                                 NaN           NaN
977                                                 NaN           NaN
978                                                 NaN           NaN
...                                                 ...           ...
5692                                               True         False
5693                                               True         False
5708                                               True         False
6040                                               True         False
6041                                               True         False

     lower(description) contains supermarket        \
                                        self other
974                                      NaN   NaN
975                                      NaN   NaN
976                                      NaN   NaN
977                                      NaN   NaN
978                                      NaN   NaN
...                                      ...   ...
5692                                     NaN   NaN
5693                                     NaN   NaN
5708                                     NaN   NaN
6040                                     NaN   NaN
6041                                     NaN   NaN

                                               old_tags  \
                                                   self
974   Friends transfers,MoneyIn,Monzo,Night,Spending...
975                                                 NaN
976   Friends transfers,MoneyIn,Monzo,Night,Spending...
977                                                 NaN
978                                                 NaN
...                                                 ...
5692                                                NaN
5693                                                NaN
5708                                                NaN
6040                                                NaN
6041                                                NaN

                                                         \
                                                  other
974   Friends transfers,MoneyIn,Monzo,Night,My trans...
975                                                 NaN
976   Friends transfers,MoneyIn,Monzo,Night,My trans...
977                                                 NaN
978                                                 NaN
...                                                 ...
5692                                                NaN
5693                                                NaN
5708                                                NaN
6040                                                NaN
6041                                                NaN

                                                     id

974   MZNd20191125t233052ap500itx_00009pKsAbsrSt4zXm...
975   MZNd20191210t142548an1000itx_00009ppBETntAyjYA...
976   MZNd20200111t232250ap600itx_00009quHbQgmXUc1jr...
977   MZNd20200114t105909an1000itx_00009qzQm1xegiZdd...
978   MZNd20200114t105949an800itx_00009qzQphFZdHijMt...
...                                                 ...
5692                    RVLTd20230430t131932an1394i3955
5693                     RVLTd20230430t140505an100i3956
5708                    RVLTd20230508t011402an1198i3967
6040                   RVLTd20231204t112824an1167i31209
6041                    RVLTd20231204t120811an200i31210

[1162 rows x 45 columns]

In [43]:
# cols = comps.columns
# cols = list({c[0] for c in comps.columns})
cols

['lower(description) contains category: entertainment',
 'lower(description) contains hotel',
 'lower(description) contains transfer',
 'lower(description) contains cash',
 'tags not_contains Transfer',
 'lower(description) contains tfl',
 'lower(description) contains ally',
 'lower(description) contains arms',
 'split_comma(tags) in_csv Eating out',
 'tags contains Food delivery',
 'lower(description) contains category: eating out',
 'lower(description) contains kfc',
 'split_comma(tags) in_csv My transfers,Alpha Bank,Friends transfers,Currency exchange,Home Bills,Rent',
 'lower(description) contains lidl',
 'lower(description) contains uber',
 'split_comma(tags) in_csv TFL,BorisBike,LimeBike,Uber Taxi',
 'lower(description) contains restaurant',
 'lower(description) contains eating out',
 'split_comma(tags) in_csv Super Market',
 'lower(description) contains supermarket',
 'old_tags',
 'lower(description) contains eat']

## get_col function to fetch the old and the new version of a given leaf rule

In [44]:
def get_col(col):
    res = comps[~comps[col].isna().any(axis=1)][['id', col]]
    res.columns = ['id', 'monzo', 'monzoapi']
    res['column'] = col
    res['count'] = len(res)
    return res

get_col(cols[1])

,id,monzo,monzoapi,column,count
1239,MZNd20230121t002758an1375itx_0000ARqpBFmcnQiqz...,False,True,lower(description) contains hotel,12
1596,MZNd20240202t192513an1080itx_0000AeTuNn3FZ2tSJ...,False,True,lower(description) contains hotel,12
1597,MZNd20240202t212254an1080itx_0000AeU4sw7isouH4...,False,True,lower(description) contains hotel,12
1705,MZNd20240323t194646an1100itx_0000Ag9ZzqVzFCLJm...,False,True,lower(description) contains hotel,12
1742,MZNd20241101t234616an1390itx_0000Anc9x0YApyxEj...,False,True,lower(description) contains hotel,12
1796,MZNd20241115t224457an660itx_0000Ao55fiscW6pvk8...,False,True,lower(description) contains hotel,12
1799,MZNd20241116t215302an1019itx_0000Ao75YMff4z4CE...,False,True,lower(description) contains hotel,12
1800,MZNd20241116t231711an1019itx_0000Ao7D3wXEUFwgp...,False,True,lower(description) contains hotel,12
1803,MZNd20241117t010105an930itx_0000Ao7MKrXjCRetNS...,False,True,lower(description) contains hotel,12
1893,MZNd20241207t001058an595itx_0000Aomk8g8O9gSk3v...,False,True,lower(description) contains hotel,12
2083,MZNd20250131t223533an1040itx_0000AqegOfV6PvBJs...,False,True,lower(description) contains hotel,12
2085,MZNd20250201t000441an810itx_0000AqeoLsa28AKHLQ...,False,True,lower(description) contains hotel,12

## stack all diffs together in a tidy format

In [45]:
all_diffs = pd.concat([get_col(col) for col in set(cols).difference(['id'])]).sort_values('count', ascending=False)
all_diffs

,id,monzo,monzoapi,column,count
1580,MZNd20240127t122903an676itx_0000AeGs9ri2ivfdil...,False,True,lower(description) contains eat,877
1476,MZNd20231119t192247ap10000itx_0000AbyRd7WshHL8...,False,True,lower(description) contains eat,877
1502,MZNd20231202t192907an700itx_0000AcPOsDjypexYz1...,False,True,lower(description) contains eat,877
1501,MZNd20231202t182803an700itx_0000AcPJQO02b1KzmL...,False,True,lower(description) contains eat,877
1500,MZNd20231202t175541an2100itx_0000AcPGXDrSOD1EE...,False,True,lower(description) contains eat,877
...,...,...,...,...,...
1494,MZNd20231129t121616an1000itx_0000AcIYhc53dSQmM...,False,True,lower(description) contains kfc,2
2052,MZNd20250120t123831an270itx_0000AqH1Sljub8v9kZ...,False,True,lower(description) contains arms,1
1101,MZNd20200307t170556an4650itx_00009slojvB6hqg5R...,False,True,split_comma(tags) in_csv Super Market,1
1101,MZNd20200307t170556an4650itx_00009slojvB6hqg5R...,False,True,lower(description) contains lidl,1
2022,MZNd20250109t113848an260itx_0000Apu8TpklOJrBMP...,False,True,lower(description) contains uber,1

## Columns with the most discrepancy

In [46]:
all_diffs.groupby(['column']).agg({'count':'mean'}).reset_index().sort_values('count', ascending=False)

                                               column  count
5                     lower(description) contains eat  877.0
15                                           old_tags  269.0
3    lower(description) contains category: eating out  240.0
6              lower(description) contains eating out  240.0
16                split_comma(tags) in_csv Eating out  206.0
13               lower(description) contains transfer   48.0
19  split_comma(tags) in_csv TFL,BorisBike,LimeBik...   48.0
11            lower(description) contains supermarket   27.0
2                    lower(description) contains cash   17.0
4   lower(description) contains category: entertai...   14.0
7                   lower(description) contains hotel   12.0
0                    lower(description) contains ally    9.0
12                    lower(description) contains tfl    4.0
10             lower(description) contains restaurant    4.0
17  split_comma(tags) in_csv My transfers,Alpha Ba...    3.0
20                        tags contains Food delivery    3.0
21                         tags not_contains Transfer    3.0
8                     lower(description) contains kfc    2.0
1                    lower(description) contains arms    1.0
14                   lower(description) contains uber    1.0
9                    lower(description) contains lidl    1.0
18              split_comma(tags) in_csv Super Market    1.0

asdasda

In [34]:
comb_transactions = monzo_calcs[['id']+fields].add_prefix('monzo_').merge(monzoapi_calcs[['id']+fields].add_prefix('monzoapi_'), left_on='monzo_id', right_on='monzoapi_id')
comb_transactions['id'] = comb_transactions['monzo_id']
del comb_transactions['monzo_id'], comb_transactions['monzoapi_id']
comb_transactions

,old_amount,old_datetime,old_description,old_amount_cur,old_currency,old_tags,new_amount,new_datetime,new_description,new_amount_cur,new_currency,new_tags,id
0,8.333333,2019-02-27 15:03:15,"bank:Revolut, type: TRANSFER, product: Current...",10.00,EUR,"Afternoon,Friends transfers,MoneyIn,Revolut,My...",8.333333,2019-02-27 15:03:15,"bank:Revolut, type: TRANSFER, product: Current...",10.00,EUR,"Afternoon,Friends transfers,MoneyIn,Revolut,My...",RVLTd20190227t150315ap833i3634
1,-8.333333,2019-02-27 15:08:11,"bank:Revolut, type: TRANSFER, product: Current...",-10.00,EUR,"Afternoon,Friends transfers,MoneyOut,Revolut,M...",-8.333333,2019-02-27 15:08:11,"bank:Revolut, type: TRANSFER, product: Current...",-10.00,EUR,"Afternoon,Friends transfers,MoneyOut,Revolut,M...",RVLTd20190227t150811an833i3635
2,6.666667,2019-04-11 09:06:18,"bank:Revolut, type: TOPUP, product: Current, c...",8.00,EUR,"Alpha Bank,MoneyIn,Morning,Revolut,My transfer...",6.666667,2019-04-11 09:06:18,"bank:Revolut, type: TOPUP, product: Current, c...",8.00,EUR,"Alpha Bank,MoneyIn,Morning,Revolut,My transfer...",RVLTd20190411t090618ap666i3636
3,-4.850000,2019-04-13 18:06:40,"bank:Revolut, type: CARD_PAYMENT, product: Cur...",-5.82,EUR,"Afternoon,GiffGaff,MoneyOut,Revolut,Other bill...",-4.850000,2019-04-13 18:06:40,"bank:Revolut, type: CARD_PAYMENT, product: Cur...",-5.82,EUR,"Afternoon,GiffGaff,MoneyOut,Revolut,Other bill...",RVLTd20190413t180640an485i3637
4,-0.966667,2019-04-25 10:06:35,"bank:Revolut, type: TRANSFER, product: Current...",-1.16,EUR,"Alpha Bank,MoneyOut,Morning,Revolut,My transfe...",-0.966667,2019-04-25 10:06:35,"bank:Revolut, type: TRANSFER, product: Current...",-1.16,EUR,"Alpha Bank,MoneyOut,Morning,Revolut,My transfe...",RVLTd20190425t100635an96i3638
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6310,-25.140000,2025-02-03 20:21:36,"bank:Monzo, type: Card payment, name: Lidl, em...",-25.14,GBP,"MoneyOut,Monzo,Night,Super Market,Food,Living ...",-25.140000,2025-02-03 20:21:36,"bank:MonzoAPI, other_fields: {merchant_feedbac...",-25.14,GBP,"MoneyOut,Monzo,Night,Super Market,Food,Living ...",MZNd20250203t202136an2514itx_0000Aqkhz36zNJ4iA...
6311,500.000000,2025-02-05 14:39:09,"bank:TRD212, action: Deposit, notes: Transacti...",500.00,GBP,"Afternoon,MoneyIn,Trading212,My transfers,Spen...",500.000000,2025-02-05 14:39:09,"bank:TRD212, action: Deposit, notes: Transacti...",500.00,GBP,"Afternoon,MoneyIn,Trading212,My transfers,Spen...",TRD212d20250205t143909ap50000i5
6312,-2642.740000,2025-02-07 19:14:24,"bank:TRD212, action: Withdrawal, raw_id: 8ea50...",-2642.74,GBP,"Afternoon,MoneyOut,Trading212,Spending,All",-2642.740000,2025-02-07 19:14:24,"bank:TRD212, action: Withdrawal, raw_id: 8ea50...",-2642.74,GBP,"Afternoon,MoneyOut,Trading212,Spending,All",TRD212d20250207t191424an264274i6
6313,3642.740000,2025-02-11 16:35:10,"bank:TRD212, action: Deposit, raw_id: 76b170f5...",3642.74,GBP,"Afternoon,MoneyIn,Trading212,Spending,All",3642.740000,2025-02-11 16:35:10,"bank:TRD212, action: Deposit, raw_id: 76b170f5...",3642.74,GBP,"Afternoon,MoneyIn,Trading212,Spending,All",TRD212d20250211t163510ap364274i7
6314,1000.000000,2025-02-21 22:16:35,"bank:TRD212, action: Deposit, notes: Transacti...",1000.00,GBP,"MoneyIn,Night,Trading212,My transfers,Spending...",1000.000000,2025-02-21 22:16:35,"bank:TRD212, action: Deposit, notes: Transacti...",1000.00,GBP,"MoneyIn,Night,Trading212,My transfers,Spending...",TRD212d20250221t221635ap100000i8

In [38]:
all_diffs[['monzo', 'monzoapi']].value_counts()

old    new
True   False    1566
False  True     1030
Name: count, dtype: int64

In [40]:
all_diffs['cm'] = all_diffs.apply(lambda row: 'tn' if row['monzo'] and not row['monzoapi'] else 'fp' if not row['monzo'] and row['monzoapi'] else None, axis=1)
all_diffs['cm'].value_counts()

cm
tn    1566
fp    1030
Name: count, dtype: int64

In [42]:
col = 'description'
rule = all_diffs[all_diffs['column']=='lower(description) contains eat'].merge(comb_transactions[['id', f'monzo_{col}', f'monzoapi_{col}']], on='id')
print(rule['cm'].value_counts())
rule

cm
fp    877
Name: count, dtype: int64

,id,old,new,column,count,cm,old_description,new_description
0,MZNd20241029t162317an1779itx_0000AnVIsIMMjZ06x...,False,True,lower(description) contains eat,877,fp,"bank:Monzo, type: Card payment, name: Zelal Su...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
1,MZNd20250108t200000an730itx_0000ApsmhJJuNhs7cj...,False,True,lower(description) contains eat,877,fp,"bank:Monzo, type: Card payment, name: Masons A...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
2,MZNd20250120t123831an270itx_0000AqH1Sljub8v9kZ...,False,True,lower(description) contains eat,877,fp,"bank:Monzo, type: Card payment, name: Transpor...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
3,MZNd20250118t184950an1554itx_0000AqDPZbGrXTw3d...,False,True,lower(description) contains eat,877,fp,"bank:Monzo, type: Card payment, name: Aldi, em...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
4,MZNd20250119t103839an270itx_0000AqEmFdUy2WgVx5...,False,True,lower(description) contains eat,877,fp,"bank:Monzo, type: Card payment, name: Transpor...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
...,...,...,...,...,...,...,...,...
872,MZNd20230213t204047an260itx_0000ASeFEhov86rsnE...,False,True,lower(description) contains eat,877,fp,"bank:Monzo, type: Card payment, name: Transpor...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
873,MZNd20230218t150741ap1000itx_0000ASo84qxrWKHLc...,False,True,lower(description) contains eat,877,fp,"bank:Monzo, type: Card payment, name: Fold, em...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
874,MZNd20230213t195231an3897itx_0000ASeAvcN2ldo3H...,False,True,lower(description) contains eat,877,fp,"bank:Monzo, type: Card payment, name: Traid - ...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
875,MZNd20230213t195611an790itx_0000ASeBFwalILtt0t...,False,True,lower(description) contains eat,877,fp,"bank:Monzo, type: Card payment, name: German D...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
876,MZNd20230218t015843an250itx_0000ASmzfHqtw7H9mw...,False,True,lower(description) contains eat,877,fp,"bank:Monzo, type: Card payment, name: Fold, em...","bank:MonzoAPI, other_fields: {merchant_feedbac..."

In [19]:
s = """bank:MonzoAPI, other_fields: {merchant_feedback_uri: monzo://dynamic_form?account_id=acc_00009gKdwGX8EWtkPJAM7t&auto_navigation=true&form_id=merchant-feedback%3Amonzo-transaction&metadata%5Btransaction_id%5D=tx_0000AoN9t3wJQT7nc0ZnUH, user_id: user_00009gKbN4Ell5hAMFcn57, merchant.disable_feedback: False, is_load: False, can_add_to_tab: True, merchant.address.latitude: 56.3961347, merchant.address.city: Perth, metadata.token_unique_reference: DSHRMC000024062819687bd087b64096a6a099b67a19f0b7, scheme: mastercard, can_be_made_subscription: True, merchant.emoji: 🍺, metadata.standin_correlation_id: standincorrelation_b992591cd672ab945dbe12a8eaeffbf7, dedupe_id: mclifecycle:mclifecycle_0000AoN9t0IqwjRca9fEjR:MASTERCARD_AUTH:mcauthmsg_0000AoN9szf9KM1ayfWwIk, merchant.address.approximate: False, amount_is_pending: False, categories.entertainment: -2136.0, metadata.mastercard_clearing_message_id: mcclearingmsg_0000AoO5iWiNtWBwsDaj1V, metadata.ledger_committed_timestamp_earliest: 2024-11-24T15:56:59.429Z, merchant.group_id: grp_00009B2GgRR2hexhTqxFqb, metadata.mastercard_lifecycle_id: mclifecycle_0000AoN9t0IqwjRca9fEjR, metadata.mastercard_auth_message_id: mcauthmsg_0000AoN9szf9KM1ayfWwIk, merchant.address.postcode: PH1 5SZ, can_be_excluded_from_breakdown: True, metadata.mastercard_card_id: mccard_0000AFIXMAaJVNUXPoGidV, settled: 2024-11-25T03:14:45.131Z, merchant.category: entertainment, merchant.address.short_formatted: "14 Saint Johns Place, Perth PH1 5SZ", merchant.address.zoom_level: 17.0, account_id: acc_00009gKdwGX8EWtkPJAM7t, metadata.mcc: 5812.0, merchant.logo: https://merchant-logos.monzo.com/2f0304f8d4e0208778ca13a8a0c8d007.png, merchant.atm: False, merchant.address.country: GBR, metadata.token_transaction_identifier: Ks5P86IEEXUh4ztI242IfSivNORfsaSyR6vOIRxD73r=, metadata.tokenization_method: android_pay, merchant.address.region: Scotland, include_in_spending: True, can_match_transactions_in_categorization: True, originator: False, metadata.ledger_insertion_id: entryset_0000AoN9t1xInpjY5Y2SsD, metadata.ledger_committed_timestamp_latest: 2024-11-25T03:14:45.131Z, updated: 2024-11-25T03:14:45.403Z, created_date: 2024-11-24, metadata.card_acceptor_contact_number: +447912564187, merchant.address.formatted: "14 Saint Johns Place, Perth, Scotland PH1 5SZ, United Kingdom", category: entertainment, merchant.online: False, can_split_the_bill: True, merchant.address.address: "14 Saint Johns Place", merchant.id: merch_0000AWcKyMmlxrEk1inodl, description: Willows                Perth         GBR, merchant.name: Willows, merchant.address.longitude: -3.4289627, metadata.mastercard_approval_type: full}"""
s.find('eat')

2137